export const Beautyproduct = [
    {
        _id : "1",
        name:"L'Oreal Paris Hyaluron Moisture ",
        name1:"Adds Shine & bounce 180ml",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51Y0GO9HHVL._SL1200_.jpg",
        description: " INSPIRED BY SKINCARE: Include the benefits of skincare into your hair care routine with the L’Oréal Paris Hyaluron Moisture 72H Moisture Filling Shampoo",
        price: 399,
        rating:1,
        numReviews:4,
    },
    {
     _id : "2",
        name:"Parachute Advansed Onion Hair Oil",
        name1:"Hair Growth - 200ml",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71QC+lpwnEL._SL1500_.jpg",
        description: "This Onion Hair Oil reduces hairfall, helps your hair grow longer, stronger and healthier. It contains the goodness of Onion and Coconut that makes it an effective hair growth oil",
        price: 289,
        rating:3,
        numReviews:4,
    },
    {
        _id : "3",
        name:"Maybelline New York Color ",
        name1:"Sensational Ultimattes Lipstick, 1.7 g",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41TEvQrTuoL._SL1000_.jpg",
        description: "Ultimattes are slim lipsticks delivering an extreme matte finish with a cushiony, yet comfortable lightweight feel.",
        price: 349,
        rating:0,
        numReviews:2,
    },
    {
        _id : "4",
        name:"Love Beauty ",
        name1:"Planet Argan Oil and, 400ml",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61ZpsIP0BTL._SL1000_.jpg",
        description: "Love beauty and planet argan oil and lavender aroma smooth and serene shampoo calms your frizz for hair that's oh so smooth",
        price: 599,
        rating:5,
        numReviews:12,
    },
    {
        _id : "5",
        name:"Kama Ayurveda Kumkumadi Miraculous Beauty ",
        name1:"Fluid Ayurvedic Night Serum",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61aHOFvEzwL._SL1000_.jpg",
        description: "A night serum made with the legendary Kumkumadi oil prescribed for dull, pigmented, damaged and aging skin. or nightly use only and should not be applied during the daytime.",
        price: 959,
        rating:3.5,
        numReviews:2,
    },
    {
        _id : "6",
        name:"Organic Harvest Premium Acne Control ",
        name1:"Gift Kit for Women & Girls",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/9102kty54xL._SL1500_.jpg",
        description: "Acne Control: This Organic Acne Control face wash fights acne-causing bacteria and helps in making the skin clear and blemish free. It contains antibacterial and anti-fungal agents like Neem and Tea Tree extracts which help in preventing acne, remove toxins and impurities from the skin.",
        price: 350,
        rating:4.5,
        numReviews:8,
    },
    ]