export const Electronicsproduct = [
    {
        _id : "1",
        name:"OnePlus ",
        name1:"80 cm (32 inches) Y Series HD Ready LED Smart Android TV 32Y1 (Black)",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71vZypjNkPS._SL1500_.jpg",
        description: " Resolution: HD Ready (1366x768) | Refresh Rate: 60 hertz",
        price: 14400,
        rating:4,
        numReviews:4,
    },
    {
     _id : "2",
        name:"Blue Star ",
        name1:"0.8 Tons 3 Star Inverter Split AC(Copper, 2020 Model, IC309RBTU, White)",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51+ZOn7EQCL._SL1500_.jpg",
        description: "Split AC with inverter compressor: Variable speed compressor which adjusts power depending on heat load.",
        price: 10499,
        rating:3,
        numReviews:4,
    },
    {
        _id : "3",
        name:"Quess Care ",
        name1:"Extended Warranty Plan for 2 Year for Refrigerator Between 40001 to 45000 (Email Delivery)",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51kqz9OZFHL._SL1500_.jpg",
        description: "Quess Care Extended Warranty Plan 1+2 year is effective from the start of the 2nd year since your product purchase (at the end of the manufacturer’s warranty). It is valid till the end of the 3rd year of your ownership.",
        price: 50349,
        rating:4,
        numReviews:2,
    },
    {
        _id : "4",
        name:"Samsung ",
        name1:"6.5 kg 5 Star Fully Automatic Front Load Washing Machine (12 Wash Programs, WW66R20GKSS/TL, Silver)",
        image: "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1605304770/Croma%20Assets/Large%20Appliances/Washers%20and%20Dryers/Images/8999312031774.png/mxw_2048,f_auto",
        description: "6.5 Kg, Front Load, Fully Automatic",
        price: 40599,
        rating:5,
        numReviews:12,
    },
    {
        _id : "5",
        name:"Philips ",
        name1:"Mixer Grinder - More power Less noise 750 Watt - HL7777/00",
        image: "https://cdn.staticans.com/image/tr:h-1500,w-1500,cm-pad_resize/data/philips/14-08-2021/HL7777%20Product_777%20x%20826%20pxls.jpg",
        description: "Additional 1 Year Warranty 2+1* year additional warranty coverage exclusively for products puchased from this website | Check Warranty Policy",
        price: 15999,
        rating:3.5,
        numReviews:2,
    },
    {
        _id : "6",
        name:"Intel",
        name1:"ThinkBook 14 Gen 2 ",
        image: "https://www.lenovo.com/medias/ThinkBook-14-Gen-2-Intel-1.jpg?context=bWFzdGVyfGltYWdlc3w1MTE0MXxpbWFnZS9qcGVnfGltYWdlcy9oM2UvaDM0LzEzMDMzMjMwMjcwNDk0LmpwZ3xmMzY4OGU2ZDE3OTExZGNlMWQ0MzI1YjUwYTUwY2FjZDQ3MjU5NzQ2OWU5NzQ3Mjk3Y2MxZDdkZTM2YmI0NjVj",
        description: "Turbocharge your business with the 35.5cms (14) Lenovo ThinkBook 14 Gen 2. This powerful laptop sports up to an 11th Gen Intel® Core™ processor and offers a range of robust storage and memory options",
        price: 55500,
        rating:4.5,
        numReviews:8,
    },
    ]