export const Fashionproduct = [
{
    _id : "1",
    name:"Yellow Half Sleeve T-Shirt for Men",
    name1:"100% COTTON Fabric 100% Cotton (Bio-Washed) 180 GSM",
    image: "https://zapvi.in/wp-content/uploads/2021/04/23.jpg",
    description: "Style Regular Fit: Fits just right Round Neck Half Sleeve Single Jersey, 100% COTTON Fabric 100% Cotton (Bio-Washed) 180 GSM",
    price: 400,
    rating:4,
    numReviews:4,
},
{
 _id : "2",
    name:"Men Golf Polo Shirt 500 Petrol Blue",
    name1:" short sleeve polo shirt for playing golf in mild weather",
    image: "https://contents.mediadecathlon.com/p732697/a7ceed49f385e3e13bab53fd65f40455/p732697.jpg?format=auto&quality=70&f=650x0",
    description: "Our designers, all golfers themselves, developed this short sleeve polo shirt for playing golf in mild weather.",
    price: 499,
    rating:3,
    numReviews:4,
},
{
    _id : "3",
    name:"Bulls Round Neck Men's Cotton Tshirts",
    name1:"Half Sleeves Round Neck Mens T-Shirt",
    image: "https://cdn.bikayi.app/ci/images/cac86aa7-5cdf-423e-abfb-d5e94816e4a0?alt=media&token=f3ce33cd-95d7-4ae0-b9a8-c64b2ad43668",
    description: "Product Name:* Cotton Printed Half Sleeves Round Neck Mens T-Shirt",
    price: 349,
    rating:4,
    numReviews:2,
},
{
    _id : "4",
    name:"Doodle Print Oversized T-Shirt",
    name1:"t-shirts nail the laid-back cool look",
    image: "https://cdn.shopify.com/s/files/1/1982/7331/products/021_02_3_489x.progressive.jpg?v=1643609210",
    description: "Doodling is fun! Now grab everyone's attention printed in a soft, comfortable 100% cotton jersey fabric featuring a casual ribbed knit crew neck design. This oversized t-shirt is a must-have. Pair with anything, relaxed fit t-shirts nail the laid-back cool look.    Neck Type: Round Neck",
    price: 599,
    rating:5,
    numReviews:12,
},
{
    _id : "5",
    name:"Bewakoof Men's Black The Ghost Graphic Printed Oversized Fit T-shirt",
    name1:"The Ghost Men's T-Shirt.",
    image: "https://images.bewakoof.com/t1080/men-s-black-the-ghost-graphic-printed-oversized-fit-t-shirt-503830-1655797646-1.jpg",
    description: "Explore the world of ghostly figures with this The Ghost Men's T-Shirt. Style this black t-shirt with trousers and funky sliders for a smart-casual look.",
    price: 399,
    rating:3.5,
    numReviews:2,
},
{
    _id : "6",
    name:"Long Styled White T-shirt For Men",
    name1:"HEAVY COTTON (PREMIUM QUALITY) OR MILD MACHINE WASH",
    image: "https://cdn.shopify.com/s/files/1/0528/3079/8018/products/WhatsAppImage2021-03-02at6.47.20PM_1024x1024@2x.jpg?v=1614691289",
    description: "MATERIAL AND CARE : HEAVY COTTON (PREMIUM QUALITY) OR MILD MACHINE WASH",
    price: 699,
    rating:4.5,
    numReviews:8,
},
]