export const Groceryproduct = [
    {
        _id : "1",
        name:"Dhara ",
        name1:"Rice Bran Oil Jar, 5L",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81Dg30Tyb0L._SX466_.jpg",
        description: " Fortified",
        price: 500,
        rating:4,
        numReviews:4,
    },
    {
     _id : "2",
        name:"Daawat Rozana Super,",
        name1:" Naturally Aged, Rich Aroma,Perfect Fit for Everyday Consumption Basmati Rice, 5 Kg",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/810jp1zceeL._SL1500_.jpg",
        description: "Rozana is above medium length product",
        price: 499,
        rating:3,
        numReviews:4,
    },
    {
        _id : "3",
        name:"Aashirvaad ",
        name1:"Select Sharbatti Atta, 5kg",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81l7thl5AQL._SL1500_.jpg",
        description: "Aashirvaad Select is made with 100% MP Sharbati wheat",
        price: 349,
        rating:4,
        numReviews:2,
    },
    {
        _id : "4",
        name:"Vedaka ",
        name1:"Popular Kabuli Chana, 1kg",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/91dXHBacwfL._SL1500_.jpg",
        description: "Quantity: 1kg",
        price: 140,
        rating:5,
        numReviews:12,
    },
    {
        _id : "5",
        name:"Tata Tea Premium ",
        name1:"| Desh Ki Chai | Unique Blend Crafted For Chai Lovers Across India | Black Tea | 1.5kg",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51QF8woKr5S._SX679_.jpg",
        description: "Tata Tea Premium, India Ke Liye Anokha Swad",
        price: 259,
        rating:3.5,
        numReviews:2,
    },
    {
        _id : "6",
        name:"Lizol Disinfectant Surface ",
        name1:"Floor Cleaner Liquid Refill Pack, Citrus - 1800ml | Kills 99.9% Germs | India's #1 Floor Cleaner",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61va4ZjIJwL._SL1000_.jpg",
        description: "India's No. 1 Floor Cleaner with 99.9% Germ Kill",
        price: 350,
        rating:4.5,
        numReviews:8,
    },
    ]
export default Groceryproduct;