export const Mobileproduct = [
    {
        _id : "1",
        name:"OnePlus Nord CE 2 Lite 5G ",
        name1:"(Blue Tide, 6GB RAM, 128GB Storage)",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71AvQd3VzqL._SL1500_.jpg",
        description: " => Camera: 64MP Main Camera with EIS; 2MP Depth Lens and 2MP Macro Lens; Front (Selfie) Camera: 16MP Sony IMX471",
        price: 24400,
        rating:2.5,
        numReviews:4,
    },
    {
     _id : "2",
        name:"Xiaomi Redmi 10 Prime ",
        name1:"(Phantom Black 4GB RAM 64GB | Helio G88 with extendable RAM Upto 2GB | FHD+ 90Hz Adaptive Sync Display)",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/817clKAKcqL._SL1500_.jpg",
        description: "Processor: MediaTek Helio G88 Octa-core processor with HyperEngine 2.0 ; Up to 2.0GHz clock speed;",
        price: 10499,
        rating:3.5,
        numReviews:4,
    },
    {
        _id : "3",
        name:"Samsung Galaxy A13 Blue,",
        name1:" 6GB RAM, 128GB Storage with No Cost EMI/Additional Exchange Offers, (SM-A135FLBJINS)",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81i1A1MgXBL._SL1500_.jpg",
        description: "Powerful 2.2 GHz Octa-Core Processor",
        price: 16349,
        rating:1,
        numReviews:2,
    },
    {
        _id : "4",
        name:"Apple iPhone 13 Pro Max ",
        name1:"(256GB) - Sierra Blue",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61i8Vjb17SL._SL1500_.jpg",
        description: "17 cm (6.7-inch) Super Retina XDR display with ProMotion for a faster, more responsive feel",
        price: 120599,
        rating:5,
        numReviews:12,
    },
    {
        _id : "5",
        name:"Samsung Galaxy S22 Ultra 5G ",
        name1:"Burgundy, 12GB, 256GB Storage with No Cost EMI/Additional Exchange Offers",
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71J8tz0UeJL._SL1500_.jpg",
        description: "The first Galaxy S with embedded S Pen. Write comfortably like pen on paper, turn quick notes into legible text and use Air Actions to control your phone remotely. Improved latency in Samsung Notes makes every pen stroke feel as natural as ink on paper — and you can convert those hastily written ideas into legible text.",
        price: 109999,
        rating:3.5,
        numReviews:2,
    },
    {
        _id : "6",
        name:"OPPO Reno8 5G ",
        name1:"8GB RAM, 128GB, Shimmer Gold",
        image: "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1659348243/Croma%20Assets/Communication/Mobiles/Images/258445_ypkzhz.png/mxw_2048,f_auto",
        description: "Display : 6.43 inches (16.33 cm), AMOLED, 90 Hz Refresh Rate",
        price: 29999,
        rating:4,
        numReviews:8,
    },
    ]